version: '3.3'

services:
  database:
    image: postgres:15.2
    environment:
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: password
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  database: